version: '3'
services:
  web:
    image: nginx:latest
    container_name: cad-nginx
    volumes:
      - ./code:/mnt/code/:rw
      - ./docker/web/:/etc/nginx/conf.d/
    ports:
      - 9292:80
    depends_on:
      - php
    networks:
      - net3
  php:
      build: ./docker/php/
      container_name: cad-php
      volumes:
        - ./code:/mnt/code/:rw
      depends_on:
        - mysql
      tty: true
      networks:
        - net3
  mysql:
    image: mysql:latest
    container_name: cad-mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: code_and_design
    ports:
      - 3406:3306
    networks:
      - net3


networks:
  net3:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
      config:
        - subnet: 192.168.12.0/24